FROM public.ecr.aws/lambda/provided:al2

RUN yum install -y gcc

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
ENV PATH $PATH:/root/.cargo/bin
RUN rustup install stable

VOLUME /code

VOLUME /root/.cargo/registry
VOLUME /root/.cargo/git

WORKDIR /code

ENTRYPOINT ["cargo", "build", "--release"]